version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6-buster
    steps:
      - checkout

      - restore_cache:
          key: dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y -q --no-install-recommended python3-venv
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pip install -r requirements.txt -r requirements-dev.txt

      - run:
          name: Run the code quality check
          command: make test.quality

      - run:
          name: Run the unit tests
          command: make test.unit

      - save_cache:
          key: dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths: 
            - "venv"